[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
vault_manager = "2eH4VtkkB5X5592hmuQqFQvQ9QKaTEmRZyvQgf9EWyxp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
